// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateWithKey(arg1) {
  return window['go']['main']['App']['ActivateWithKey'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteKey() {
  return window['go']['main']['App']['DeleteKey']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function LoadKey() {
  return window['go']['main']['App']['LoadKey']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SaveKey(arg1) {
  return window['go']['main']['App']['SaveKey'](arg1);
}
