// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateWithKey(arg1:string):Promise<string>;

export function Connect(arg1:string):Promise<string>;

export function DeleteKey():Promise<void>;

export function Disconnect():Promise<string>;

export function GetStatus():Promise<boolean>;

export function LoadKey():Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveKey(arg1:string):Promise<void>;
